encoder: resnet18
decoder: alexnet
algorithm: train
device: cuda
in_channels: 1
number_classes: 10
dataset: mnist
train_part: 0.7
valid_part: 0.2
seed: 42
batch_size: 32
epochs: 20
logs: /logs
checkpoints: /checkpoints
save_every: 5
optimizer: 'adam'
learning_rate: 0.001
optimizer_betas: [0.9, 0.999]
optimizer_eps: 0.00000001
weight_decay: 0.000001
scheduler: steplr
step: 15
gamma: 0.5
metrics: ['accuracy', 'precision', 'recall', 'f1_score']
loss: ce
class_names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
checkpoint: /checkpoints/best_0.05.pt