# path to image: class value
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img0.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img1.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img2.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img3.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img4.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img5.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img6.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img7.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img8.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img9.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img10.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img11.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img12.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img13.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img14.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img15.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img16.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img17.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img18.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img19.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img20.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img21.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img22.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img23.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img24.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img25.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img26.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img27.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img28.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img29.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img30.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img31.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img32.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img33.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img34.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img35.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img36.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img37.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img38.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img39.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img40.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img41.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img42.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img43.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img44.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img45.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img46.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img47.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img48.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img49.jpg: 1
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img50.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img51.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img52.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img53.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img54.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img55.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img56.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img57.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img58.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img59.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img60.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img61.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img62.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img63.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img64.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img65.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img66.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img67.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img68.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img69.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img70.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img71.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img72.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img73.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img74.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img75.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img76.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img77.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img78.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img79.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img80.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img81.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img82.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img83.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img84.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img85.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img86.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img87.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img88.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img89.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img90.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img91.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img92.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img93.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img94.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img95.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img96.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img97.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img98.jpg: 0
C:/Users/SuperPC/Downloads/OpenNN/CUSTOM/imgs/img99.jpg: 0